[google_sheets]
type = "service_account"
project_id = "contest-details-dashboard"
private_key_id = "a8b7fe491edfe9575e4d2f0a376d5b67cda1a730"
private_key = '''
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDiFfGVgOwmZ8J7
MY30yLCgoMl/YsfuSxbEZrYB2xmrqRTbQfjq3R/C/yCw9X15OM2WvkM+gXNhB7tw
acopOvytvL/EFuYOX/bacr4ncTlscLdO2gbigYrLcoyLJyR0DjwddaHMy++FMYvc
pqXsaxd59v03SWZItF2sAvTx6oeEst9+B1E8tQ77KVMG1TGB2Q8zk98WcBJqWsJs
33QbkBnOO6iI4xnZ7uRyFOcWgEct1gtmpIjHYFUt4SsB3xcR49KXTQ72qKYemaQw
41QG79n2ykD/LnuefaXytaoGguVyyI3zFe1rKg3hC0ri7ChkyOPpB0L3Tueoeab7
3WR8K3BzAgMBAAECggEAESvMfOfdR69ywGuLlg9WBuUfWKr2d11BneoVIb/zy6tc
V6jDkIb53hQFdhs3C+lqB+xsbAdl7XUqYcfPIGGIBmQDBpAcqfPU6lNzqMg7LcbD
zVvW0QY4ten9zaXL6XqZSz1/a/ADQZD5R+lqSbH6hvtg0P2kpJn6UVGqK+N9pnDQ
6E9doC99TSwMPzRcR6hBu/jIAXw9x8CSBUddrz/azTXHPjWgaa3gdMim0p4Q9NF3
QrWXAQEeCQb1ArZdJA5LkfJ6C88qoibYLS8hADXc7mR0qqUbBm+8SMkN03euFNC2
TjGihPGtgfsp8vLxNRXb/b/AsXO2t0WEcruN+yaJoQKBgQDw9/o7UbEDb6LO+dWi
A0T5bGO+9pkqUn/nFMrRwtYJoodLdplomo3/7tLv7h23/VdKxcoj+YMT+n0rv7O4
xEuq7o9DABopvuabGofmHgu189DLNNrOmj5v3Rkd4hTAdESNVtKvVsgHYsTG5nIM
JGkyIuhFO1dBBV18MC/git3m4QKBgQDwME0EqP9kJzDCEGm3QAKd58TdyjGD4R0j
Te3A/mlDAeL9E0WSUlDqjDOB+6vLPdh4dgS1+90MA2E3xd225dxE9m0Z5Ittuady
UIk+x/TSqN9UdSRz+hn9QGkpZJCgdKN44z26dmausQ4f5RTO3xZ6U0MZV6e3w7s1
JWzupvvF0wKBgEtVq5SqCIZDe4nrz59UGFdGTLTiEaaKnlQXSwVjPVlLx7KPBI0Q
bL6L4sSCFCZ2fLjytyyiEBnJ4SIxT7W/IMzywjU3LfbJKP1qwPvvfsfGzwsInjOj
Q0vjurt99/DnKJtrfni0z9qHRW/NkfA73et/wFAMqk24qK5vvjgcEh3hAoGAVgbm
vwGMn6GNzCQ2yQSrK0Vk9I9D1tldJ1T1EAfPScm2NDCf3X2QL8HRfP/YEy5uhw62
NzwjevcG7gP3mleP4j9k6j46Vi2FtOL1lT/nB0Cm5MgkK0nr3xIf2EyFpILCPj0d
0dgwhOcziOby4flzQpLp2HzVvHLlbW6fKocybDMCgYBCnEiz9PJDEfylgVDYZIt/
IZf0hBBBhtyNDSeg0FdvcvvumX55FJuqK949BmRlkLITEzBLQyn30E5lo74FPMyc
su9vHAsqV1kF2KRn4/9+HwkubOg0K/zgFRCzhFE9j7i0mojyXoQTb/TpaH73YXkC
Gr+fbcfSb9MNz65tEJDYzw==
-----END PRIVATE KEY-----
'''
client_email = "contest-dashboard@contest-details-dashboard.iam.gserviceaccount.com"
client_id = "116846163480553096023"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/contest-dashboard%40contest-details-dashboard.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
